language: scala

scala:
    - 2.11.12
    - 2.12.8
    - 2.13.0-M5

jdk:
    - oraclejdk8

script:
  - sbt -Dsbt.log.noformat=true clean +coverage +test
after_success:
  - sbt -Dsbt.log.noformat=true +coverageReport coveralls
  - bash <(curl -s https://codecov.io/bash)

# go faster on travis
sudo: false

notifications:
    email:
        - dmitry.krivaltsevich@zalando.de